apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: 811851959278.dkr.ecr.us-east-1.amazonaws.com/orders:1.0
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-orders
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-orders
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: cm-orders
          ports:
            - containerPort: 8080